#! /bin/sh

pulseaudio --start

$HOME/.config/polybar/launch.sh

feh $ feh --bg-fill --randomize $HOME/.config/bspwm/wallpaper.png & 
compton &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a 'microsoft-edge-stable' state=floating
#bspc rule -a 'google-chrome-stable' state=floating
#bspc rule -a 'google-chrome-stable' desktop=^9
bspc rule -a 'Pantalla en pantalla' state=floating


bspc config border_width 2
bspc config focused_border_color \#8f3a84
bspc config normal_border_color \#000000
bspc config window_gap          0

bspc config focus_follows_pointer false
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 20
